version: '3.3'

services:
  nginx:
    build: ./tubearchivist/nginx
    container_name: backend_nginx
    restart: always
    ports: 
      - "80:80"
    depends_on:
      - tubearchivist
  # main flask site
  tubearchivist:
    container_name: tubearchivist
    build:
      context: ./tubearchivist/web
      args:
        - INSTALL_DEBUG=1
    restart: always
    volumes:
      - ./volume/tubearchivist/data:/data
    env_file:
      - ./env/tubearchivist.env
    environment:
      - discord=gkWMk9Qupk
    expose:
      - "8080"
  # backend postgres
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data/
    env_file:
      - ./env/postgres.env
    expose:
      - "5432"
  # redis job monitor
  redis:
    image: redislabs/rejson:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./volume/redis:/data
